services:
  db:
    image: mysql:8.0
    container_name: django_contracts_db
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3306:3306"


  django:
    build: .
    container_name: django_contracts
    command: >
      sh -c "
             python /ContractSystem/manage.py collectstatic --noinput &&
             python /ContractSystem/manage.py makemigrations --no-input &&
             python /ContractSystem/manage.py migrate --no-input &&
             gunicorn ContractSystem.wsgi --bind 0.0.0.0:8000 --workers 2
            "
    ports:
      - "8000:8000"
    volumes:
      - .:/ContractSystem
    env_file:
      - .env
    depends_on:
      - db 
  nginx:
      image: nginx:alpine
      container_name: django_nginx
      volumes:
        - ./nginx.conf:/e tc/nginx/nginx.conf:ro
        - .:/ContractSystem
        - /var/www/certbot:/var/www/certbot
      ports:
        - "80:80"
        - "443:443"
      depends_on:
        - django

volumes:
  mysql_data:
