services:
  db:
    image: mysql:8.0
    container_name: django_contracts_db
    volumes:
      - ./docker-mysql-data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=230223  # Set this password
      - MYSQL_DATABASE=contracts_db
  django:
    build: .
    container_name: django_contracts
    command: >
      sh -c "
             python /ContractSystem/manage.py collectstatic --noinput &&
             python /ContractSystem/manage.py makemigrations --no-input &&
             python /ContractSystem/manage.py migrate --no-input &&
             gunicorn ContractSystem.wsgi --bind 0.0.0.0:8000 --workers 2
            "
    ports:
      - "8000:8000"
    volumes:
      - .:/ContractSystem
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - celery_worker
      - celery_beat

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    command: celery -A ContractSystem worker --loglevel=info
    volumes:
      - .:/ContractSystem
    depends_on:
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A ContractSystem beat --loglevel=info
    volumes:
      - .:/ContractSystem
    depends_on:
      - redis
    env_file:
      - .env
      
networks:
  default:
    driver: bridge